### ISSUE TITLE
Player gets stuck in match still even on new honfigurator, CPU usage goes up over time

### ISSUE THREAD

**Issue by Nestyzxc** [HoNfigurator/HoNfigurator-Central#31]
![image](https://github.com/HoNfigurator/HoNfigurator-Central/assets/23737124/03c6b949-13d8-48a6-af40-95d001208034)
![image](https://github.com/HoNfigurator/HoNfigurator-Central/assets/23737124/2c725b1e-05a3-4d3d-8674-56bb6a3e2ceb)

**Comment by frankthetank001** [comment]
Resolved a long time ago by removing idle players during the match over phase after a certain duration
